import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Linkedin 2",
  description: "Generated by eraskush",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
    <html lang="en">
      <body className="min-h-screen flex flex-col" >
        
        {/*Toaster */}

        <header className="border-b sticky top-0 bg-white z-50"><Header /></header>

        <div className="bg-[#f4f2ED] flex-1 w-full ">
        <main>
          {children}
        </main>
        </div>
      </body>
    </html>

</ClerkProvider>
  );
}
